version: "1.0"

services: 
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@123Abc$3212
  order-service:
    container_name: order-service
    image: ${DOCKER_REGISTRY-}order-service
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    ports:
      - 5000:80
    depends_on: 
      - mssql
  payment-service:
    container_name: payment-service
    image: ${DOCKER_REGISTRY-}payment-service
    build:
      context: .
      dockerfile: src/PaymentService/PaymentService.API/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - mssql
  product-sync-service:
    container_name: product-sync-service
    image: ${DOCKER_REGISTRY-}product-sync-service
    build:
      context: .
      dockerfile: src/ProductSyncService/ProductSyncService.API/Dockerfile
    ports:
      - 5002:80
    depends_on: 
      - mssql