version: "1.0"

services: 
  api:
    depends_on: 
      - mssql
    image: ${DOCKER_REGISTRY -} sample-ddd-netcore
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:80"
      - "50001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT = Development
      - ASPNETCORE_URLS = https://+443;http://+:80
  mssql:
    