version: "1.0"

services: 
  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@123Abc$3212
    volumes:
      - db:/var/lib/mssql/data
  redis-stack:
    container_name: redis
    restart: always
    image: redis/redis-stack:latest
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - cache:/data
    ports:
      - 6379:6379
  identity:
    container_name: identity
    image: luuthuong/identity:v1
    build:
      context: .
      dockerfile: src/Identity/Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: on-failure:3
    depends_on: 
      - mssql
  order-service:
    container_name: order-services
    image: luuthuong/order-service:v1
    build:
      context: .
      dockerfile: src/OrderService/OrderService.API/Dockerfile
    ports:
      - 5000:80
    depends_on: 
      - mssql
      - redis-stack
  payment-service:
    container_name: payment-service
    image: luuthuong/payment-service:v1
    build:
      context: .
      dockerfile: src/PaymentService/PaymentService.API/Dockerfile
    ports:
      - 5001:80
    depends_on: 
      - mssql
      - redis-stack
  product-sync-service:
    container_name: product-sync-service
    image: luuthuong/product-sync-service:v1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: src/Services/ProductSyncService/ProductSyncService.API/Dockerfile
    restart: on-failure:3
    links:
      - mssql
      - redis-stack
    ports:
      - 5002:80
    depends_on: 
      - mssql
      - redis-stack
volumes: 
  cache:
    driver: local
  db:
    driver: local