name: Publicsh Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_docker_hub:
    name: "Push docker image to github package registry"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Fetch version
        shell: bash
        run: |
          # Restore .NET tools
          dotnet tool restore

          # Get the version number
          echo "VERSION=$(dotnet minver -t v -m 0.1 --default-pre-release-phase preview -v e -d ./src/CounterService)" >> $GITHUB_ENV
          
      - name: ProductService - Extract metadata for Docker
        id: product-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/product-sync-service
          tags: |
            type=raw,value=${{ env.VERSION }}
          flavor: |
            latest=true

      - name: ProductSync Service - Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./src/Services/ProductSyncService/ProductSyncService.API/Dockerfile
          context: .
          push: true
          tags: ${{ steps.product-meta.outputs.tags }}
          labels: ${{ steps.product-meta.outputs.labels }}
